
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class StudentDetails extends javax.swing.JFrame {

    /**
     * Creates new form StudentDetails
     */
    int click = 0;
    public StudentDetails() {
        initComponents();
        //this.getRootPane().setDefaultButton(searchButton);
        this.getRootPane().setDefaultButton(srcButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(30);
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        deptField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        srcButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rsz_iiuclogo.gif"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1, 0, 720, 110);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255,100));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Student Details");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(150, 70, 165, 30);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(49, 113, 109, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Age");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(49, 157, 109, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setText("Email");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(49, 199, 109, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("Department");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 250, 109, 22);

        nameField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel2.add(nameField);
        nameField.setBounds(164, 112, 213, 30);

        ageField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });
        jPanel2.add(ageField);
        ageField.setBounds(164, 156, 54, 26);

        emailField.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jPanel2.add(emailField);
        emailField.setBounds(164, 198, 230, 30);

        deptField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel2.add(deptField);
        deptField.setBounds(164, 242, 213, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 255));
        jLabel8.setText("ID");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(90, 20, 30, 40);

        srcButton.setBackground(new java.awt.Color(51, 255, 51));
        srcButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        srcButton.setForeground(new java.awt.Color(255, 0, 0));
        srcButton.setText("Search");
        srcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcButtonActionPerformed(evt);
            }
        });
        jPanel2.add(srcButton);
        srcButton.setBounds(250, 19, 140, 40);
        jPanel2.add(searchField);
        searchField.setBounds(130, 25, 110, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(160, 110, 430, 290);
        jPanel2.setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iiuc.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1, 0, 720, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void srcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcButtonActionPerformed
        // TODO add your handling code here:
        String id = searchField.getText();
        //int i = Integer.parseInt(id);

        String query = "select *from student where id = "+id;
        String Name = "";
        String Age = "";
        String Email = "";
        String Dept = "";
        try{
            ResultSet rs = DBUTILS.queryExecute(query);
            if(rs.next()){
                Name = rs.getString("name");
                Age = rs.getString("age");
                Email = rs.getString("email");
                Dept = rs.getString("dept");
            }
        } catch(Exception e){

        }
        if(!"".equals(Name)){
            nameField.setText(Name);
            ageField.setText(Age);
            deptField.setText(Dept);
            emailField.setText(Email);
        }
        else{
            JOptionPane.showMessageDialog(this,"Student ID not Found","Error",JOptionPane.ERROR_MESSAGE);
        }
        nameField.setEditable(false);
        ageField.setEditable(false);
        deptField.setEditable(false);
        emailField.setEditable(false);
    }//GEN-LAST:event_srcButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JTextField deptField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton srcButton;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
}
